using Test
using GLLVM

@testset "smoke" begin
    @test 1 + 1 == 2
end

include("test_likelihood.jl")
include("test_packing.jl")
include("test_fit.jl")
include("test_fixed_effects.jl")
include("test_W_and_diag.jl")
include("test_phy.jl")
include("test_signed_sigma_phy.jl")
include("test_sparse_phy.jl")
include("test_ppca_init.jl")
include("test_em_fa.jl")
include("test_lowrank_cholesky.jl")
include("test_confint.jl")
include("test_confint_profile.jl")
include("test_confint_bootstrap.jl")
include("test_confint_derived.jl")
include("test_profile_derived_fix.jl")
include("test_takahashi_selinv.jl")
include("test_em_louis.jl")
include("test_em_sparse_estep_default.jl")
include("test_node_gradient.jl")
include("test_fit_phylo.jl")
include("test_families.jl")
include("test_binomial_laplace.jl")
include("test_poisson_laplace.jl")
include("test_negbin_laplace.jl")
include("test_beta_laplace.jl")
include("test_ordinal_laplace.jl")
include("test_gamma_laplace.jl")
include("test_family_forwarddiff_gradients.jl")
include("test_binomial_fit.jl")
include("test_poisson_fit.jl")
include("test_nb_fit.jl")
include("test_beta_fit.jl")
include("test_gamma_fit.jl")
include("test_ordinal_fit.jl")
include("test_confint_families.jl")
include("test_fit_gllvm.jl")
include("test_postfit.jl")
include("test_structured_schur.jl")
include("test_structured_poisson_laplace.jl")
include("test_structured_cov.jl")
include("test_twopart_substrate.jl")
include("test_delta_fit.jl")
include("test_delta_postfit.jl")
include("test_hurdle_poisson.jl")
include("test_hurdle_nb.jl")
include("test_quality.jl")
