using Test
using GLLVM

# All suites run under one outer testset so that a failure in any included file
# does not abort the run before later files execute: included `@testset`s nest
# (Test uses dynamic scoping), accumulate, and only this root throws at the end —
# so one CI run reports every failure across all files, not just the first.
@testset "GLLVM.jl" begin
    @testset "smoke" begin
        @test 1 + 1 == 2
    end

    include("test_likelihood.jl")
    include("test_packing.jl")
    include("test_fit.jl")
    include("test_fixed_effects.jl")
    include("test_W_and_diag.jl")
    include("test_phy.jl")
    include("test_signed_sigma_phy.jl")
    include("test_sparse_phy.jl")
    include("test_ppca_init.jl")
    include("test_em_fa.jl")
    include("test_lowrank_cholesky.jl")
    include("test_confint.jl")
    include("test_confint_profile.jl")
    include("test_confint_bootstrap.jl")
    include("test_confint_derived.jl")
    include("test_profile_derived_fix.jl")
    include("test_takahashi_selinv.jl")
    include("test_em_louis.jl")
    include("test_em_sparse_estep_default.jl")
    include("test_node_gradient.jl")
    include("test_fit_phylo.jl")
    include("test_families.jl")
    include("test_binomial_laplace.jl")
    include("test_poisson_laplace.jl")
    include("test_negbin_laplace.jl")
    include("test_beta_laplace.jl")
    include("test_ordinal_laplace.jl")
    include("test_gamma_laplace.jl")
    include("test_binomial_fit.jl")
    include("test_poisson_fit.jl")
    include("test_nb_fit.jl")
    include("test_beta_fit.jl")
    include("test_gamma_fit.jl")
    include("test_exponential.jl")
    include("test_ordinal_fit.jl")
    include("test_fit_gllvm.jl")
    include("test_postfit.jl")
    include("test_ordination.jl")
    include("test_model_selection.jl")
    include("test_structured_cov.jl")
    include("test_twopart_substrate.jl")
    include("test_delta_fit.jl")
    include("test_delta_postfit.jl")
    include("test_hurdle_poisson.jl")
    include("test_hurdle_nb.jl")
    include("test_delta_gamma.jl")
    include("test_zero_inflated.jl")
    include("test_confint_family.jl")
    include("test_summary_table.jl")
    include("test_covariates.jl")
    include("test_formula.jl")
    include("test_simulate.jl")
    include("test_species_covariates.jl")
    include("test_fourthcorner.jl")
    include("test_row_effects.jl")
    include("test_constrained_ordination.jl")
    include("test_quadratic.jl")
    include("test_ordered_beta.jl")
    include("test_variational.jl")
    include("test_variational_binomial.jl")
    include("test_variational_negbin.jl")
    include("test_variational_gamma.jl")
    include("test_variational_beta.jl")
    include("test_variational_dgamma.jl")
    include("test_va_vs_laplace.jl")
    include("test_quality.jl")
end
